<html><head><base href=""><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Zaggy Social - AI Content Creation</title>
<style>
:root {
  --bakery: #D4A373;
  --flower: #FF69B4;
  --coffee: #6F4E37;
  --pet: #98DBC6;
  --business: #2C3E50;
  --renovation: #34495E;
  --boutique: #DB7093;
  --restaurant: #228B22;
  --primary: #2A2356;
  --secondary: #FF6B6B;
  --accent: #4ECDC4;
  --light: #F7F7F7;
  --dark: #1A1A1A;
}

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: 'Inter', sans-serif;
}

body {
  background: var(--light);
  color: var(--dark);
  line-height: 1.6;
}

.nav {
  background: var(--primary);
  padding: 1rem;
  position: fixed;
  width: 100%;
  top: 0;
  z-index: 100;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.logo {
  color: white;
  font-size: 1.5rem;
  font-weight: 700;
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.hero {
  margin-top: 80px;
  padding: 4rem 2rem;
  text-align: center;
  background: linear-gradient(135deg, var(--primary), var(--accent));
  color: white;
}

.example-posts {
  display: block;
  max-width: 1200px; /* Increased to allow for varying widths */
  margin: 2rem auto;
  padding: 0 2rem;
  position: relative;
}

.post-card {
  width: 100%;
  max-width: 800px; /* Allow cards to be different widths */
  margin-left: auto;
  margin-right: auto;
  margin-bottom: 4rem;
  opacity: 0;
  transform: translateX(-100px);
  transition: all 1.5s cubic-bezier(0.34, 1.56, 0.64, 1);
  transform-origin: center center;
  padding: 2rem;
  border-radius: 12px;
  display: flex;
  flex-direction: column;
}

.post-card:nth-child(even) {
  transform: translateX(100px); /* Alternate starting positions */
}

.post-card.visible {
  opacity: 1;
  transform: translateX(0) scale(1);
}

.post-card.exit {
  opacity: 0;
  transform: translateX(100px) scale(0.95);
  transition: all 1.2s cubic-bezier(0.34, 1.56, 0.64, 1);
}

.post-card.exit-reverse {
  opacity: 0;
  transform: translateX(-100px) scale(0.95);
  transition: all 1.2s cubic-bezier(0.34, 1.56, 0.64, 1);
}
